INSERT INTO STATUS (nome, sigla) VALUES ('Decolado', 'DC'),('Partindo','PT'),('Atrasado','AT');
INSERT INTO PILOTOS (nome, identificador) VALUES ('Alvin M. Johnston','AMJ'),('Steve Harris','SH'),('Doru Davidovici','DD'),('Gabriel Voisin','GV'),('Joao Ribeiro de Barros','JRB'),('Ricardo Kirk','RK'),('Edu Chaves','EC'),('Jose Costa','JC');
INSERT INTO CIDADES (nome, sigla) VALUES ('Brasilia','DF'),('Sao Paulo','SP'),('Rio de Janeiro','RJ'),('Salvador','SA'),('Belo Horizonte','BH'),('Natal','RN'),('Joao Pessoa','PB'),('Recife','PE'),('Porto Alegre','RS');
INSERT INTO AERONAVES (nome) VALUES ('Airbus A320'),('Airbus A300'),('Boeing 707'),('Boeing 757'),('Embraer ERJ-190'),('Boeing 787'),('Airbus A380'),('Boeing 767');

INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('0093','06:45:00','10:45:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Airbus A300'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP'),(SELECT ID FROM CIDADES WHERE SIGLA = 'BH'),(SELECT ID FROM PILOTOS WHERE NOME = 'Joao Ribeiro de Barros'),(SELECT ID FROM STATUS WHERE SIGLA = 'AT'));
INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('7656','16:30:00','18:30:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Boeing 757'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP'),(SELECT ID FROM CIDADES WHERE SIGLA = 'RS'),(SELECT ID FROM PILOTOS WHERE NOME = 'Ricardo Kirk'),(SELECT ID FROM STATUS WHERE SIGLA = 'DC'));
INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('1582','06:10:00','09:35:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Embraer ERJ-190'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SA'),(SELECT ID FROM PILOTOS WHERE NOME = 'Gabriel Voisin'),(SELECT ID FROM STATUS WHERE SIGLA = 'PT'));
INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('6424','10:25:00','14:35:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Airbus A320'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP'),(SELECT ID FROM CIDADES WHERE SIGLA = 'RN'),(SELECT ID FROM PILOTOS WHERE NOME = 'Jose Costa'),(SELECT ID FROM STATUS WHERE SIGLA = 'PT'));
INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('1898','06:45:00','11:35:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Airbus A380'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP',(SELECT ID FROM CIDADES WHERE SIGLA = 'PE'),(SELECT ID FROM PILOTOS WHERE NOME = 'Edu Chaves'),(SELECT ID FROM STATUS WHERE SIGLA = 'AT'));
INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('2897','06:45:00','10:35:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Boeing 767'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP'),(SELECT ID FROM CIDADES WHERE SIGLA = 'RJ'),(SELECT ID FROM PILOTOS WHERE NOME = 'Doru Davidovici'),(SELECT ID FROM STATUS WHERE SIGLA = 'DC'));
INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('3456','07:30:00','07:50:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Boeing 707'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP'),(SELECT ID FROM CIDADES WHERE SIGLA = 'DF'),(SELECT ID FROM PILOTOS WHERE NOME = 'Steve Harris'),(SELECT ID FROM STATUS WHERE SIGLA = 'DC'));
INSERT INTO VOOS (numero,horario_saida,horario_chegada,aeronave_id,cidade_origem_id,cidade_destino_id,piloto_id,status_id) VALUES ('9876','06:55:00','10:35:00',(SELECT ID FROM AERONAVES WHERE NOME = 'Boeing 787'),(SELECT ID FROM CIDADES WHERE SIGLA = 'SP',(SELECT ID FROM CIDADES WHERE SIGLA = 'JP'),(SELECT ID FROM PILOTOS WHERE NOME = 'Alvin M. Johnston'),(SELECT ID FROM STATUS WHERE SIGLA = 'AT'));

